### ISSUE TITLE
kibana50-x-pack directory

### ISSUE THREAD

**Issue by FlorianBruckner** [FreshPorts/freshports#37]
kibana50-x-pack installs into /usr/local/www/kibana50/plugins/x-pack/x-pack

Kibana expects the plugin to be in /usr/local/www/kibana50/plugins/x-pack instead (package.json is required in this directory).

Can be verified by running

`# /usr/local/bin/node /usr/local/www/kibana50/src/cli_plugin list
`
which returns 

`x-pack@5.0.2
`
when installed correctly, but 

```

/usr/local/www/kibana50/src/cli_plugin/list/list.js:26
        throw new Error('Unable to read package.json file for plugin ' + filename);
        ^

Error: Unable to read package.json file for plugin x-pack
    at /usr/local/www/kibana50/src/cli_plugin/list/list.js:26:15
    at Array.forEach (native)
    at list (/usr/local/www/kibana50/src/cli_plugin/list/list.js:13:44)
    at Command.processCommand (/usr/local/www/kibana50/src/cli_plugin/list/index.js:38:25)
    at Command.<anonymous> (/usr/local/www/kibana50/src/cli/command.js:90:18)
    at Command.listener (/usr/local/www/kibana50/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/www/kibana50/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/local/www/kibana50/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/www/kibana50/src/cli_plugin/cli.js:54:9)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/www/kibana50/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)


```
otherwise

**Comment by dlangille** [comment]
This appears to be an issue with the port, not with http://freshports.org/

If so, you want to open a ticket at http://bugs.freebsd.org/

**Comment by dlangille** [comment]
For your convenience, there is a link to report a bug at the top of the page: http://www.freshports.org/textproc/kibana50/

Look for the little bug-like icon on the second line

**Comment by FlorianBruckner** [comment]
Yes, indeed - thanks.
