### ISSUE TITLE
code processing is expecting UTF-8, when it should be ASCII

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#379]
```
...
2022.08.09 17:27:04 git-delta.sh e7fa4bfd1b60bef52f2dcdc1cb807d9842d1fb27
2022.08.09 17:27:04 git-delta.sh 886a56788375d3b3a235a1bc0acfe8c51ab95c1a
2022.08.09 17:27:04 git-delta.sh 8f93153c2719d922b8292cd74ff4f5f6d69861d6
2022.08.09 17:27:04 git-delta.sh d78045dfdfa235483277fdcc33cc62df6d5fef57
2022.08.09 17:27:04 git-delta.sh /usr/local/libexec/freshports/git-to-freshports-xml.py --repo ports --path /var/db/ingress/repos/ports --branch 2020Q1 --commit-range 758edde62973c24d29b0c082f9cab9329b405194..28b4da349ddcc9e8493e8c3d013eb2fc4107098a --spooling /var/db/ingress/message-queues/spooling --output /var/db/ingress/message-queues/incoming
Traceback (most recent call last):
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 255, in <module>
    main()
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 195, in main
    text.text = commit.message.strip()
  File "src/lxml/etree.pyx", line 1041, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2022.08.09 17:27:17 git-delta.sh /usr/local/libexec/freshports/git-to-freshports-xml.py result: 1
```

**Comment by dlangille** [comment]
Testing in my home directory:

```
[dev-ingress01 dan ~/tmp] % /usr/local/libexec/freshports/git-to-freshports-xml.py --repo ports --path ~/src/FreeBSD/ports --branch 2020Q1 --commit-range 758edde62973c24d29b0c082f9cab9329b405194..28b4da349ddcc9e8493e8c3d013eb2fc410709 --spooling ~/tmp/spooling --output ~/tmp/incoming  --verbose
Traceback (most recent call last):
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 255, in <module>
    main()
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 195, in main
    text.text = commit.message.strip()
  File "src/lxml/etree.pyx", line 1041, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
[dev-ingress01 dan ~/tmp] %                                                                                                                                                19:03:12
```

**Comment by dlangille** [comment]
The last bits in `/var/log/freshports/freshports.log` were:

```
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[INFO] Processing commit 'bc0620b2474bc31161f4a20388e28c0d91c8a92c MFH: r522460'
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Getting commit datetime
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Commit datetime: 2020-01-08 21:40:19
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Writing commit date
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Writing commit time
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Writing OS entry
Aug  9 19:03:12 dev-ingress01 git-to-freshports-xml.py[16725]:[DEBUG] Writing commit message
```

**Comment by dlangille** [comment]
This confirms that commit does demonstrate the problem:

```
[dev-ingress01 dan ~/tmp] % /usr/local/libexec/freshports/git-to-freshports-xml.py --repo ports --path ~/src/FreeBSD/ports --branch 2020Q1 -c bc0620b2474bc31161f4a20388e28c0d91c8a92c --spooling ~/tmp/spooling --output ~/tmp/incoming  --verbose                                     
Traceback (most recent call last):
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 255, in <module>
    main()
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 195, in main
    text.text = commit.message.strip()
  File "src/lxml/etree.pyx", line 1041, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
[dev-ingress01 dan ~/tmp] %                                                                                                                                                19:05:28
```

**Comment by dlangille** [comment]
The commit in question: https://cgit.freebsd.org/ports/commit/?id=bc0620b2474bc31161f4a20388e28c0d91c8a92c
