### ISSUE TITLE
sqlmap package issue.

### ISSUE THREAD

**Issue by runtomaker** [FreshPorts/freshports#558]
sqlmap package must be update to stable version.

Run:

root@host:~ # sqlmap -u http://example.com/

`        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.3.12#pip}
|_ -| . [)]     | .'| . |
|___|_  [']_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 20:26:04 /2024-04-12/

[20:26:04] [ERROR] wrong modification time of '/usr/local/lib/python3.9/site-packages/sqlmap/extra/shutils/duplicates.py'
[20:26:04] [ERROR] wrong modification time of '/usr/local/lib/python3.9/site-packages/sqlmap/extra/shutils/newlines.py'
[20:26:04] [CRITICAL] code integrity check failed (turning off automatic issue creation). You should retrieve the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlmap/sqlmap.py", line 166, in main
    init()
  File "/usr/local/lib/python3.9/site-packages/sqlmap/lib/core/option.py", line 2687, in init
    loadBoundaries()
  File "/usr/local/lib/python3.9/site-packages/sqlmap/lib/parse/payloads.py", line 89, in loadBoundaries
    parseXmlNode(root)
  File "/usr/local/lib/python3.9/site-packages/sqlmap/lib/parse/payloads.py", line 44, in parseXmlNode
    for element in node.getiterator("boundary"):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
[20:26:04] [WARNING] you haven't updated sqlmap for more than 1593 days!!!

[*] ending @ 20:26:04 /2024-04-12/

`

**Comment by dlangille** [comment]
Hello,

This isn't the best place to report troubles with ports. The port maintainers will not see them here.  From https://www.freshports.org/about.php: "FreshPorts is not the place to report errors or request changes"

At https://www.freshports.org/security/sqlmap/ - Find the two bug icons

![bugs](https://github.com/FreshPorts/freshports/assets/1626436/ca743eb0-b548-40ec-bc4c-dc3736734723)

The left one will search for existing bugs, the right one will start a new bug report.

Hope that helps. We can leave this issue open until you've got that new bug report open.

**Comment by runtomaker** [comment]
Thanks. I found now this bug link.
